### ISSUE TITLE
Issue with Removing/Adding Widgets

### ISSUE THREAD

**Issue by mmstick** [gtk-rs/gtk#192]
I've made a program that generates a list of widgets contained within a `ScrolledWindow` and I want users to be able to refresh the list based on the entry inside of a `SearchEntry`. My only problem is that I've had no success in figuring out how to remove the current `ScrolledWindow` and replace it with a newly-generated `ScrolledWindow` after pressing enter on the `SearchEntry`. I can at least get the text from the `SearchEntry` and do things with that text, like creating a new list with that text, but replacing the pre-existing `ScrolledWindow` is my problem.

I thought about simply overwriting the current list's variable with a newly-created list, but I'm unable to do so inside the `connect_key_press_event` closure because it's a `Fn` closure instead of `FnMut`, hence modifying external variables outside of the closure while inside the closure is disallowed.

I thought about removing the original `ScrolledWindow` and just slapping on a newly-generated one inside the closure, but then I have no idea how I'd be able to remove that newly-created `ScrolledWindow` the next time the closure is called since there will no longer be a visible reference to it that I can call.

My other issue is that I apparently cannot get newly-created `ScrolledWindow`s to appear. Only the first `ScrolledWindow` I create works, but subsequent `ScrolledWindow`s are invisible -- taking up space but not showing anything, even if I manually set `set_visible(true)` and use `pack_start(&scrolled, true, true, 0)`.

**Comment by gkoz** [comment]
I'm not sure why you'd want to remove the `ScrollWindow` rather than replace its contents. Some limited example demonstrating what you intend to do would be helpful.

Although `Fn` closures are somewhat limiting, `Rc` and `RefCell` allow shared ownership and mutability in such cases (they're not needed for widgets because those already are clonable and don't need to be mutable).

As to any widgets not showing up this is usually solved by calling `show_all` on the appropriate container.

**Comment by mmstick** [comment]
[This is my source code](https://github.com/mmstick/systemd-manager/tree/search-integration). Integration of the search and replace functionality is happening in `main.rs`. I'm at a loss as to how to go about fixing this.

**Comment by gkoz** [comment]
I would rather put `scrolled_window` in the `main` and change `generate_services` to take a reference to `ScrolledWindow`. Then the event handler can have a clone of `scrolled_window` moved into it. 

Generally this kind of UI is supposed to be implemented via [TreeView](https://developer.gnome.org/gtk3/stable/TreeWidget.html).

**Comment by mmstick** [comment]
Taking it by reference from main doesn't seem to solve it. If I manually create a clone with the following:

```
let mut units_widget_clone = units_widget.clone();
```

and try then use it with:

```
systemd_gui::generate_services(&units_widget_clone, &search_word);
```

I simply get an error when triggering the event and nothing happens:

```
Gtk-CRITICAL **: gtk_scrolled_window_add: assertion 'child_widget == NULL' failed
```

If I otherwise just use it directly without manually cloning it, the same thing happens:

```
Gtk-CRITICAL **: gtk_scrolled_window_add: assertion 'child_widget == NULL' failed
```

If I try to replace the value of it with a new, clean state inside the event with:

```
units_widget = gtk::ScrolledWindow::new(None, None).unwrap();
```

I get the same error as before:

```
error: cannot assign to captured outer variable in an `Fn` closure
```

**Comment by gkoz** [comment]
Apparently talking about code doesn't work too well. I'll need a small functional independent example to offer more helpful suggestions.

**Comment by mmstick** [comment]
This is the key parts of code in question. [Full Source](https://github.com/mmstick/systemd-manager/tree/search-integration)

I am currently creating a `gtk::ScrolledWindow` named `units_widget` in `main()` and passing it as a reference to `systemd_gui:generate_services()` to attach the boxes of units to it. When the enter key is pressed, the program takes the contents of the `search_entry` and passes it to `systemd_gui::generate_services()` to collect a new list with units containing the keyword in their names. I would simply like to replace the contents of the currently added `gtk::ScrolledWindow` with the newly-generated list, but getting it to replace the list is my issue.

### main.rs
```
    let vbox = gtk::Box::new(gtk::Orientation::Vertical, 0).unwrap();
    let search_entry = gtk::SearchEntry::new().unwrap();
    let window = systemd_gui::create_main_window();
    let units_widget = gtk::ScrolledWindow::new(None, None).unwrap();
    systemd_gui::generate_services(&units_widget, "");

    vbox.pack_start(&search_entry, false, false, 0);
    vbox.pack_start(&units_widget, true, true, 0);
    window.add(&vbox);
    window.show_all();

    {
        window.connect_key_press_event(move |_, key| {
            match key.keyval as i32 {
                key::Escape => gtk::main_quit(),
                key::Return => {
                    let search_word = search_entry.get_text().unwrap();
                    println!("{}", search_word);
                    units_widget = gtk::ScrolledWindow::new(None, None).unwrap();
                    systemd_gui::generate_services(&units_widget, &search_word);
                },
                _ => ()
            }
            gtk::signal::Inhibit(false)
        });
    }
```

### systemd_gui.rs
```
pub fn generate_services(scrolled_window: &gtk::ScrolledWindow, keyword: &str) {
    ........
    scrolled_window.add(&service_list);
}
```

**Comment by gkoz** [comment]
I can't build and run this locally, obviously.

**Comment by mmstick** [comment]
You can if you git the full source though.

**Comment by mmstick** [comment]
Pretty much just this
```
git clone https://github.com/mmstick/systemd-manager/ -b search-integration
cd systemd-manager
cargo run
```

**Comment by mmstick** [comment]
Still can't figure this out, now with yet another application built similarly. The closures for signatures don't allow modifying variables because they aren't FnMut, so there's no way to update the GUI with new contents, such as refreshing the list of articles. I can only add new widgets to GUI versus updating previous ones.

```
src/phoronix/gui.rs:45:63: 45:71 error: cannot borrow captured outer variable in an `Fn` closure as mutable
src/phoronix/gui.rs:45     refresh_button.connect_clicked(move |_| refresh_page(&mut articles, &mut article_box));
                                                                                     ^~~~~~~~
src/phoronix/gui.rs:45:36: 45:90 help: consider changing this closure to take self by mutable reference
src/phoronix/gui.rs:45     refresh_button.connect_clicked(move |_| refresh_page(&mut articles, &mut article_box));
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/phoronix/gui.rs:45:78: 45:89 error: cannot borrow captured outer variable in an `Fn` closure as mutable
src/phoronix/gui.rs:45     refresh_button.connect_clicked(move |_| refresh_page(&mut articles, &mut article_box));
                                                                                                    ^~~~~~~~~~~
src/phoronix/gui.rs:45:36: 45:90 help: consider changing this closure to take self by mutable reference
src/phoronix/gui.rs:45     refresh_button.connect_clicked(move |_| refresh_page(&mut articles, &mut article_box));
```

**Code in Question:** https://github.com/mmstick/phoronix-reader/commit/6d2a4d690d94840ece43467ce7b612e6bc658456

**How to Build:**
git clone https://github.com/mmstick/phoronix-reader/ -b refresh-page
cd phoronix-reader
cargo run

**Comment by GuillaumeGomez** [comment]
@mmstick: You can modify data in such closures by using `Rc<RefCell<_>>` types. I did it in my [process-viewer](https://github.com/GuillaumeGomez/process-viewer) example (which reminds me that I should update it...).

**Comment by gkoz** [comment]
Closing due to inactivity.
Feel free to reopen with a small standalone demonstration of a problem.
